include: package:flutter_lints/flutter.yaml

analyzer:

linter:
  rules:

    prefer-trailing-comma: true
    non_constant_identifier_names: false
    prefer_single_quotes: true

    cancel_subscriptions: true
    avoid_dynamic_calls: true
    prefer_void_to_null: true
    use_build_context_synchronously (experimental): true,
    empty_constructor_bodies: true
    prefer_const_constructors: true
    prefer_conditional_assignment: true
    sort_unnamed_constructors_first: false
    sort_child_properties_last: true
    prefer_constructors_over_static_methods: false
    always_declare_return_types: true
    unnecessary_await_in_return: true
    unnecessary_const: true
    unnecessary_lambdas: true
    eol_at_end_of_file: true
    lines_longer_than_80_chars: false
    prefer_relative_imports: true

    avoid_returning_null_for_future: true
    unawaited_futures: true
    await_only_futures: true
    annotate_overrides: true
    avoid_void_async: true
    always_put_control_body_on_new_line: false

