name: mydex
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
# Core
  async: ^2.8.2
  dartz: ^0.10.1
  rxdart: ^0.27.3
  mobx: ^2.0.6+1
  mobx_codegen: ^2.0.4
  flutter_mobx: ^2.0.4
# Local
  shared_preferences: ^2.0.13
# Network
  dio: ^4.0.4
  pretty_dio_logger: ^1.2.0-beta-1
  retrofit: ^3.0.1+1
# DI
  get_it: ^7.2.0
  get_it_mixin: ^3.1.4
# Code Gen
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
# UI
  device_preview: ^1.0.0
  flutter_screenutil: ^5.3.1
  material_design_icons_flutter: ^5.0.6595

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.19.5
  test_cov: ^1.0.1
  coverage: ^1.0.3
  mocktail: ^0.3.0
  build_test: ^2.1.5
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  freezed: ^1.1.0
  json_serializable: ^6.1.5
  network_image_mock: ^2.0.1
  retrofit_generator: ^3.0.1+1


flutter:
  uses-material-design: true
